### PR TITLE
Conversion code for Merlin Medipix data

### PR DESCRIPTION
**Pull request by M0hsend**
Code to import Merlin Medipix (TEM / 4D-STEM) data using dask, reshaping using the exposure times appearing in the MIB header characters and saving output images and full / binned HDF5 files. The code is to be run on the DLS cluster - an example bash file is also provided.

### CODE REVIEW

**Comment by M0hsend** [comment]
TODO for this code:
- Adding 4DSTEM loading from multiple MIB files, e.g. 1000 frames per file
- Checking the effect of above on speed
- Dask improvement, e.g. using dask.delayed by defining more functions?

**Comment by TomSlater** [comment]
The importing and reshaping functions look good to me. They work on my local PC in any case.

Should add to the TODO:

- Write unit tests for all functions

**Comment by TomSlater** [comment]
- Acquire minimum size datasets for the tests too!

**Comment by chrisallen80** [comment]
Run on user data MG22549-6 no errors. Shall we merge now (so there is a stable and working version on ePSIC-DLS and start new pull requests for Mohsen's TODO list above and unit tests...

**Comment by dnjohnstone** [comment]
Hi @TomSlater would it be possible to merge this one up so that I can make a new PR adding docstrings etc please?

**Comment by TomSlater** [comment]
Merged now.

We have some test datasets now so I'll write up tests for functions (hopefully next week).

**Pull request merged**
